### ISSUE TITLE
Italian Glossary is ready on google sheet

### ISSUE THREAD

**Issue by groundrace** [open-contracting/glossary#1]
Just to let you know that Italian glossary has been completed and is setup on both the Google sheet and Transifex. I can't push here and I believe isn't needed me to open a pull request for it.

**Comment by jpmckinney** [comment]
Thanks! We're making a few updates to the glossary, so I'll pull in the Italian glossary once that's done.

**Comment by jpmckinney** [comment]
Closed by #2
